# 作業のリスト(配列順にTicketの生成が試行される)
tasks:
 - 'task6'
 - 'task5'
 - 'task4'
 - 'task3'
 - 'task2'
 - 'task1'

# 作業生成時の依存関係
task_dependency:
 task6:
  - 'task3'
  - 'task4'
 task5:
  - 'task3'
 task4:
  - 'task3'
 task3:
  - 'task1'
  - 'task2'
 task2:
 task1:

# 休憩時間(分:秒)
rest: '0:03'

# 作業時間(分:秒)
work_time: '0:20'
min_work_time:
 test: '0:04'
 task1: '0:02'
 overwrite: '0:01'

mongodb: 'localhost:27017'
mongodb_session: 'testdb'


# データの置き場所とパースのルール
image_blob_globpath: '/Users/ahashimoto/annotator/blob_images/*/camera?/*/*.png'
image_blob_id_regex: '\A.*\/blob_images\/(.+)\.png\Z'
recipe_blob_globpath: '/Users/ahashimoto/annotator/blob_recipes/*'
recipe_blob_id_regex: '\A.*\/blob_recipes/(.+)\Z'
recipe_id_regex: '.*(2014RC\d\d).*'
