# mongodbへの接続情報
mongodb: 'localhost:27017'
mongodb_session: 'testdb'

# 基本的な合計作業時間(分:秒) ログイン時に表示される初期終了時刻を決める
standard_total_work_time: '180:00'
# 休憩時間(分:秒)
rest_time: '0:03'
# 休憩までの作業時間(分:秒)
work_time: '20:00'

# 上書きするかどうかの質問の回答表示時間
min_overwrite_time: '0:01'

# 同じチケットプールの作業をどれくらい続けるか
chain_duration: '0:10'

timezone: 'Asia/Tokyo'

my_tasks:
 default:
  minimum_micro_task_num: 1
  min_work_time: '0:01'
  checker_min_work_time: '0:01'
 task1:
  #minimum_micro_task_num: 2
  min_work_time: '0:05'
  checker_min_work_time: '0:03'
  data_path: '$ANNOTATE_ROOT/blob_images/'
  glob_pattern: '*/extract/camera?/*/*.png'
  blob_id_regex: '.*\/blob_images\/(.+)\.png\Z'

  # 画像表示サイズ
  # 1040 x 776
  image_width: 416 #520
  image_height: 310.4 #388
  modulation: 150
  min_similarity: 0.8

 task2:
  minimum_micro_task_num: 2
  min_work_time: '0:05'
  data_path: '$ANNOTATE_ROOT/blob_recipes'
  glob_pattern: '/*'
  blob_id_regex: '\A/(.+)\Z'
  recipe_id_regex: '.*(20\d\d..\d\d).*'
  synonym_file: '$ANNOTATE_ROOT/../recipesentenceclustering/ontology/synonym.tsv'
  overview: 'overview.jpg'

# task3:
#  minimum_micro_task_num: 2
#  min_work_time: '0:05'
#  # 依存関係にある場合，名前をアルファベット順でソートしたときに依存先が前になるようにtask名をつける
#  # じゃないとticket生成の時に変になる．
#  dependency:
#   - 'task1'
#   - 'task2'
#  data_path: '$ANNOTATE_ROOT/blob_images'
#  glob_pattern: '*/extract/camera?/*/*.png'
#  # 画像表示サイズ
#  # 1040 x 776
#  image_width: 416 #520
#  image_height: 310.4 #388
#
 task4:
  minimum_micro_task_num: 2
  min_work_time: '0:05'
  data_path: '$ANNOTATE_ROOT/blob_images'
  glob_pattern: '/*/videos'
  data_id_regex: '\A.*/blob_images/(.+)/videos\Z'
  video_dir: 'videos'

  video_extension: '.webm'
  segment_file: 'segments.csv'
  # 画像表示サイズ
  # 1040 x 776
  image_width: 416 #520
  image_height: 310.4 #388

 task_pedes_count:
  minimum_micro_task_num: 1
  min_work_time: '0:03'
  data_path: '$ANNOTATE_ROOT/data_pedes_count'
  glob_pattern: '/cam*_line*/*'
  data_id_regex: '\A.*/(cam.+?_line.+?/\d{8}).*\Z'
  cam_id_regex: '.*(cam.+?_line.+?)/.*\Z'
  blob_id_regex: '\A/(cam.+?_line.+)\Z'
  image_extension: '.png'
  timestamp_files: 'timestamps/*.txt'
  line_file: 'line.png'
  # 画像表示サイズ
  # 1040 x 776
  image_width: 416 #520
  image_height: 310.4 #388








